services:
  edge:
    networks:
      - envy
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-edge:stable
    build: apps/edge
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ISCLOUDFLARE=False
      - DOCKER=True
  database:
    networks:
      - envy
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-database:stable
    build: apps/database
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ISCLOUDFLARE=False
      - DOCKER=True
  auth:
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-auth:stable
    build: apps/auth
    networks:
      - envy
    environment:
      - DOCKER=True
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSWORD_MIN_LENGTH=8
      - PASSWORD_MAX_LENGTH=32
      - USERNAME_MIN_LENGTH=3
      - USERNAME_MAX_LENGTH=32
      - ISSUER=your_issuer
      - AUTH_KEY=your_auth_key
      - ISSECURE=False
      - ISCLOUDFLARE=False
  core:
    networks:
      - envy
    image: ghcr.io/orbical-dev/envybase-core:stable
    build: apps/core
    ports:
      - "3000:3000"
  mongodb:
    networks:
      - envy
    image: mongo:latest
    volumes:
     - mongodb_data:/data/db

  redis:
    networks:
      - envy
    image: redis:latest
    volumes:
     - redis_data:/data

networks:
  envy:
volumes:
  mongodb_data:
  redis_data: